- hosts: docker
  tasks:
  - name: "Install httpd"
    package:
      name: "httpd"
      state: present
  - name: "copy webpage"
    copy:
      src: "index.html"
      dest: "/var/www/html"
  - name: "start httpd services"
    command: "/usr/sbin/httpd"
